<template>
  <div>
    <div class="form-outer">
      <div class="label">部门：</div>
      <el-input
        class="item"
        v-model="searchForm.content"
        placeholder="请输入部门名称"
      ></el-input>

      <el-button class="button" @click="handleSearch">查询</el-button>
      <el-button class="button" @click="handleReset">重置</el-button>
      <el-button class="button" type="primary">新增</el-button>
    </div>
    "num": "1", "type": "技能培训", "content": "动设备、润滑油相关知识", "bm":
    "丙烯酸装置", "sz": "黄苍昊", "spry": "广新实习人员", "pxsj": "2020-11-27",
    "pxks": "2", "rc": "10", "zks": "20", "fy": "200", "fyqx": "培训费打卡",
    "jsqk": "结算", "jssj": "2021-1-12", "rzsj": "2021-1-12", "fyfsbm":
    "丙烯酸装置-管理"
    <el-table border :data="tableData" style="width: 100%">
      <el-table-column fixed prop="num" label="序号" width="100">
      </el-table-column>
      <el-table-column prop="type" label="培训类型" width="200">
      </el-table-column>
      <el-table-column prop="content" label="培训内容" width="200">
      </el-table-column>
      <el-table-column prop="bm" label="培训部门"> </el-table-column>
      <el-table-column prop="bm" label="培训部门"> </el-table-column
      ><el-table-column prop="bm" label="培训部门"> </el-table-column
      ><el-table-column prop="bm" label="培训部门"> </el-table-column
      ><el-table-column prop="bm" label="培训部门"> </el-table-column
      ><el-table-column prop="bm" label="培训部门"> </el-table-column
      ><el-table-column prop="bm" label="培训部门"> </el-table-column
      ><el-table-column prop="bm" label="培训部门"> </el-table-column>
      <el-table-column fixed="right" label="操作" width="200">
        <template slot-scope="scope">
          <el-button
            type="text"
            size="small"
            @click="handleEdit(scope.row, scope.$index)"
            >下载</el-button
          >
          <el-button type="text" style="color: red" size="small"
            >删除</el-button
          >
        </template>
      </el-table-column>
    </el-table>
  </div>
</template>

<script>
import data1 from "@/assets/jh.json";
export default {
  data() {
    return {
      searchForm: {
        planName: "",
        content: "",
        startDate1: [],
      },
      tableData: [
        {
          num: "1",
          type: "技能培训",
          content: "动设备、润滑油相关知识",
          bm: "丙烯酸装置",
          sz: "黄苍昊",
          spry: "广新实习人员",
          pxsj: "2020-11-27",
          pxks: "2",
          rc: "10",
          zks: "20",
          fy: "200",
          fyqx: "培训费打卡",
          jsqk: "结算",
          jssj: "2021-1-12",
          rzsj: "2021-1-12",
          fyfsbm: "丙烯酸装置-管理",
        },
        {
          num: "2",
          type: "技能培训",
          content: "静设备简介、法兰及固件",
          bm: "丙烯酸装置",
          sz: "倪伟国",
          spry: "广新实习人员",
          pxsj: "2020-11-27",
          pxks: "2",
          rc: "10",
          zks: "20",
          fy: "200",
          fyqx: "培训费打卡",
          jsqk: "结算",
          jssj: "2021-1-12",
          rzsj: "2021-1-12",
          fyfsbm: "丙烯酸装置-管理",
        },
        {
          num: "3",
          type: "技能培训",
          content: "氧化工艺与蒸汽工艺知识了解",
          bm: "丙烯酸装置",
          sz: "黄禹沁",
          spry: "广新实习人员",
          pxsj: "2020-11-30",
          pxks: "2",
          rc: "22",
          zks: "44",
          fy: "200",
          fyqx: "培训费打卡",
          jsqk: "结算",
          jssj: "2021-1-12",
          rzsj: "2021-1-12",
          fyfsbm: "丙烯酸装置-管理",
        },
        {
          num: "4",
          type: "技能培训",
          content: "丁酯流程及简介",
          bm: "丙烯酸装置",
          sz: "曹时锟",
          spry: "广新实习人员",
          pxsj: "2020-11-30",
          pxks: "2",
          rc: "22",
          zks: "44",
          fy: "200",
          fyqx: "培训费打卡",
          jsqk: "结算",
          jssj: "2021-1-12",
          rzsj: "2021-1-12",
          fyfsbm: "丙烯酸装置-管理",
        },
        {
          num: "5",
          type: "技能培训",
          content: "装置级安全教育",
          bm: "丙烯酸装置",
          sz: "顾忆锋",
          spry: "广新实习人员",
          pxsj: "2020-12-1",
          pxks: "2",
          rc: "22",
          zks: "44",
          fy: "200",
          fyqx: "培训费打卡",
          jsqk: "结算",
          jssj: "2021-1-12",
          rzsj: "2021-1-12",
          fyfsbm: "丙烯酸装置-管理",
        },
        {
          num: "6",
          type: "技能培训",
          content: "催化焚烧、废物处理工艺知识了解",
          bm: "丙烯酸装置",
          sz: "黄禹沁",
          spry: "广新实习人员",
          pxsj: "2020-12-1",
          pxks: "2",
          rc: "22",
          zks: "44",
          fy: "200",
          fyqx: "培训费打卡",
          jsqk: "结算",
          jssj: "2021-1-12",
          rzsj: "2021-1-12",
          fyfsbm: "丙烯酸装置-管理",
        },
        {
          num: "7",
          type: "技能培训",
          content: "动设备、润滑油相关知识",
          bm: "丙烯酸装置",
          sz: "黄苍昊",
          spry: "广新实习人员",
          pxsj: "2020-12-2",
          pxks: "2",
          rc: "12",
          zks: "24",
          fy: "200",
          fyqx: "培训费打卡",
          jsqk: "结算",
          jssj: "2021-1-12",
          rzsj: "2021-1-12",
          fyfsbm: "丙烯酸装置-管理",
        },
        {
          num: "8",
          type: "技能培训",
          content: "静设备、密封件相关知识",
          bm: "丙烯酸装置",
          sz: "倪伟国",
          spry: "广新实习人员",
          pxsj: "2020-12-2",
          pxks: "2",
          rc: "12",
          zks: "24",
          fy: "200",
          fyqx: "培训费打卡",
          jsqk: "结算",
          jssj: "2021-1-12",
          rzsj: "2021-1-12",
          fyfsbm: "丙烯酸装置-管理",
        },
        {
          num: "9",
          type: "技能培训",
          content: "公辅工程概况介绍",
          bm: "丙烯酸装置",
          sz: "谢华剑",
          spry: "广新实习人员",
          pxsj: "2020-12-3",
          pxks: "2",
          rc: "13",
          zks: "26",
          fy: "200",
          fyqx: "培训费打卡",
          jsqk: "结算",
          jssj: "2021-1-12",
          rzsj: "2021-1-12",
          fyfsbm: "丙烯酸装置-管理",
        },
        {
          num: "10",
          type: "技能培训",
          content: "公辅工程PID流程讲解",
          bm: "丙烯酸装置",
          sz: "谢华剑",
          spry: "广新实习人员",
          pxsj: "2020-12-4",
          pxks: "2",
          rc: "13",
          zks: "26",
          fy: "200",
          fyqx: "培训费打卡",
          jsqk: "结算",
          jssj: "2021-1-12",
          rzsj: "2021-1-12",
          fyfsbm: "丙烯酸装置-管理",
        },
        {
          num: "11",
          type: "技能培训",
          content: "废气催化焚烧、废液焚烧",
          bm: "丙烯酸装置",
          sz: "李益",
          spry: "广新实习人员",
          pxsj: "2020-12-7",
          pxks: "2",
          rc: "15",
          zks: "30",
          fy: "200",
          fyqx: "培训费打卡",
          jsqk: "结算",
          jssj: "2021-1-12",
          rzsj: "2021-1-12",
          fyfsbm: "丙烯酸装置-管理",
        },
        {
          num: "12",
          type: "技能培训",
          content: "罐区PID图、作业注意事项、日常工作内容",
          bm: "丙烯酸装置",
          sz: "李文军",
          spry: "广新实习人员",
          pxsj: "2020-12-9",
          pxks: "2",
          rc: "15",
          zks: "30",
          fy: "200",
          fyqx: "培训费打卡",
          jsqk: "未结算",
          jssj: "领导费用暂不结算",
          fyfsbm: "丙烯酸装置-管理",
        },
        {
          num: "13",
          type: "技能培训",
          content: "DAA标准曲线制作 MEHQ标准曲线制作",
          bm: "SAP装置",
          sz: "施幸浩",
          spry: "韩舒逸、刘朝龙、陈思捷、韩文吉、顾伟程、周晓薇",
          pxsj: "2020-12-7",
          pxks: "2",
          rc: "6",
          zks: "12",
          fy: "200",
          fyqx: "培训费打卡",
          jsqk: "结算",
          jssj: "2021-1-12",
          rzsj: "2021-1-12",
          fyfsbm: "SAP装置-管理",
        },
        {
          num: "14",
          type: "技能培训",
          content: "SILICA标准曲线制作 卡尔费休水分仪操作",
          bm: "SAP装置",
          sz: "施幸浩",
          spry: "韩舒逸、刘朝龙、陈思捷、韩文吉、顾伟程、周晓薇",
          pxsj: "2020-12-10",
          pxks: "2",
          rc: "6",
          zks: "12",
          fy: "200",
          fyqx: "培训费打卡",
          jsqk: "结算",
          jssj: "2021-1-12",
          rzsj: "2021-1-12",
          fyfsbm: "SAP装置-管理",
        },
        {
          num: "15",
          type: "技能培训",
          content: "催化剂车间概况",
          bm: "催化剂装置",
          sz: "陈超",
          spry: "何伟、周朱捷",
          pxsj: "2020-12-8",
          pxks: "2",
          rc: "2",
          zks: "4",
          fy: "200",
          fyqx: "培训费打卡",
          jsqk: "结算",
          jssj: "2021-1-12",
          rzsj: "2021-1-12",
          fyfsbm: "催化剂装置-管理",
        },
        {
          num: "16",
          type: "技能培训",
          content: "催化剂车间级安全教育",
          bm: "催化剂装置",
          sz: "陈超",
          spry: "何伟、周朱捷",
          pxsj: "2020-12-8",
          pxks: "2",
          rc: "2",
          zks: "4",
          fy: "200",
          fyqx: "培训费打卡",
          jsqk: "结算",
          jssj: "2021-1-12",
          rzsj: "2021-1-12",
          fyfsbm: "催化剂装置-管理",
        },
        {
          num: "17",
          type: "技能培训",
          content: "催化剂溶解、干燥工段工艺",
          bm: "催化剂装置",
          sz: "吕剑峰",
          spry: "何伟、周朱捷",
          pxsj: "2020-12-9",
          pxks: "2",
          rc: "2",
          zks: "4",
          fy: "200",
          fyqx: "培训费打卡",
          jsqk: "结算",
          jssj: "2021-1-12",
          rzsj: "2021-1-12",
          fyfsbm: "催化剂装置-管理",
        },
        {
          num: "18",
          type: "技能培训",
          content: "正极项目概况",
          bm: "催化剂装置",
          sz: "高韵之",
          spry: "何伟、周朱捷",
          pxsj: "2020-12-9",
          pxks: "2",
          rc: "2",
          zks: "4",
          fy: "200",
          fyqx: "培训费打卡",
          jsqk: "结算",
          jssj: "2021-1-12",
          rzsj: "2021-1-12",
          fyfsbm: "催化剂装置-管理",
        },
        {
          num: "19",
          type: "技能培训",
          content: "正极工艺介绍",
          bm: "催化剂装置",
          sz: "王宏亮",
          spry: "何伟、周朱捷",
          pxsj: "2020-12-10",
          pxks: "2",
          rc: "2",
          zks: "4",
          fy: "200",
          fyqx: "培训费打卡",
          jsqk: "结算",
          jssj: "2021-1-12",
          rzsj: "2021-1-12",
          fyfsbm: "催化剂装置-管理",
        },
        {
          num: "20",
          type: "技能培训",
          content: "催化剂混合、成型工段工艺",
          bm: "催化剂装置",
          sz: "陶思俊",
          spry: "何伟、周朱捷",
          pxsj: "2020-12-10",
          pxks: "2",
          rc: "2",
          zks: "4",
          fy: "200",
          fyqx: "培训费打卡",
          jsqk: "结算",
          jssj: "2021-1-12",
          rzsj: "2021-1-12",
          fyfsbm: "催化剂装置-管理",
        },
        {
          num: "21",
          type: "技能培训",
          content: "催化剂混合、成型工段工艺",
          bm: "催化剂装置",
          sz: "史乾源",
          spry: "何伟、周朱捷",
          pxsj: "2020-12-10",
          pxks: "2",
          rc: "2",
          zks: "4",
          fy: "200",
          fyqx: "培训费打卡",
          jsqk: "结算",
          jssj: "2021-1-12",
          rzsj: "2021-1-12",
          fyfsbm: "催化剂装置-管理",
        },
        {
          num: "22",
          type: "技能培训",
          content: "正极现场学习及质检简介",
          bm: "催化剂装置",
          sz: "高韵之",
          spry: "何伟、周朱捷",
          pxsj: "2020-12-11",
          pxks: "2",
          rc: "2",
          zks: "4",
          fy: "200",
          fyqx: "培训费打卡",
          jsqk: "结算",
          jssj: "2021-1-12",
          rzsj: "2021-1-12",
          fyfsbm: "催化剂装置-管理",
        },
        {
          num: "23",
          type: "新进人员培训",
          content: "安全教育-入司安全教育、HSE管理体系",
          bm: "安全环保部",
          sz: "何军峰",
          spry: "华理认知实习（大四本科生）",
          pxsj: "2020-12-8",
          pxks: "2",
          rc: "50",
          zks: "100",
          fy: "400",
          fyqx: "培训费打卡",
          jsqk: "结算",
          jssj: "2021-1-12",
          rzsj: "2021-1-12",
          fyfsbm: "安全环保部",
        },
        {
          num: "24",
          type: "新进人员培训",
          content: "生产装置现场参观",
          bm: "催化剂装置",
          sz: "陈超",
          spry: "华理认知实习（大四本科生）",
          pxsj: "2020-12-8",
          pxks: "2",
          rc: "50",
          zks: "100",
          fy: "400",
          fyqx: "培训费打卡",
          jsqk: "结算",
          jssj: "2021-1-12",
          rzsj: "2021-1-12",
          fyfsbm: "催化剂装置-管理",
        },
        {
          num: "25",
          type: "新进人员培训",
          content: "生产装置现场参观",
          bm: "生产管理部",
          sz: "汪伟",
          spry: "华理认知实习（大四本科生）",
          pxsj: "2020-12-8",
          pxks: "2",
          rc: "50",
          zks: "100",
          fy: "400",
          fyqx: "培训费打卡",
          jsqk: "结算",
          jssj: "2021-1-12",
          rzsj: "2021-1-12",
          fyfsbm: "生产管理部",
        },
        {
          num: "26",
          type: "新进人员培训",
          content: "环保管理知识/职业卫生/事故案例分析",
          bm: "安全环保部",
          sz: "杨晨",
          spry: "华理认知实习（大四本科生）",
          pxsj: "2020-12-9",
          pxks: "2",
          rc: "50",
          zks: "100",
          fy: "400",
          fyqx: "培训费打卡",
          jsqk: "结算",
          jssj: "2021-1-12",
          rzsj: "2021-1-12",
          fyfsbm: "安全环保部",
        },
        {
          num: "27",
          type: "新进人员培训",
          content: "消防安全知识",
          bm: "安全环保部",
          sz: "王国强",
          spry: "华理认知实习（大四本科生）",
          pxsj: "2020-12-9",
          pxks: "2",
          rc: "50",
          zks: "100",
          fy: "400",
          fyqx: "培训费打卡",
          jsqk: "结算",
          jssj: "2021-1-12",
          rzsj: "2021-1-12",
          fyfsbm: "安全环保部",
        },
        {
          num: "28",
          type: "新进人员培训",
          content: "消防器材使用（灭火器使用、消防呼吸面罩穿戴）",
          bm: "安全环保部",
          sz: "王国强",
          spry: "华理认知实习（大四本科生）",
          pxsj: "2020-12-9",
          pxks: "2",
          rc: "50",
          zks: "100",
          fy: "400",
          fyqx: "培训费打卡",
          jsqk: "结算",
          jssj: "2021-1-12",
          rzsj: "2021-1-12",
          fyfsbm: "安全环保部",
        },
        {
          num: "29",
          type: "新进人员培训",
          content: "公司发展规划、企业文化介绍",
          bm: "人力资源部",
          sz: "瞿红",
          spry: "华理认知实习（大四本科生）",
          pxsj: "2020-12-10",
          pxks: "2",
          rc: "50",
          zks: "100",
          fy: "400",
          fyqx: "培训费打卡",
          jsqk: "未结算",
          jssj: "领导费用暂不结算",
          fyfsbm: "人力资源部",
        },
        {
          num: "30",
          type: "新进人员培训",
          content: "丙烯酸酯化单元生产工艺及概况",
          bm: "技术部",
          sz: "张岚",
          spry: "华理认知实习（大四本科生）",
          pxsj: "2020-12-10",
          pxks: "2",
          rc: "50",
          zks: "100",
          fy: "400",
          fyqx: "培训费打卡",
          jsqk: "结算",
          jssj: "2021-1-12",
          rzsj: "2021-1-12",
          fyfsbm: "技术部",
        },
        {
          num: "31",
          type: "新进人员培训",
          content: "岗位成才故事",
          bm: "丙烯酸装置",
          sz: "冯彪",
          spry: "华理认知实习（大四本科生）",
          pxsj: "2020-12-10",
          pxks: "2",
          rc: "50",
          zks: "100",
          fy: "400",
          fyqx: "培训费打卡",
          jsqk: "未结算",
          jssj: "领导费用暂不结算",
          fyfsbm: "丙烯酸装置-管理",
        },
        {
          num: "32",
          type: "新进人员培训",
          content: "丙烯酸氧化单元生产工艺及概况",
          bm: "技术部",
          sz: "段力志",
          spry: "华理认知实习（大四本科生）",
          pxsj: "2020-12-11",
          pxks: "2",
          rc: "50",
          zks: "100",
          fy: "400",
          fyqx: "培训费打卡",
          jsqk: "结算",
          jssj: "2021-1-12",
          rzsj: "2021-1-12",
          fyfsbm: "技术部",
        },
        {
          num: "33",
          type: "新进人员培训",
          content: "PDH单元生产工艺及概况",
          bm: "技术部",
          sz: "金涛",
          spry: "华理认知实习（大四本科生）",
          pxsj: "2020-12-11",
          pxks: "2",
          rc: "50",
          zks: "100",
          fy: "400",
          fyqx: "培训费打卡",
          jsqk: "结算",
          jssj: "2021-1-12",
          rzsj: "2021-1-12",
          fyfsbm: "技术部",
        },
        {
          num: "34",
          type: "新进人员培训",
          content: "生产装置现场参观",
          bm: "生产管理部",
          sz: "杨菁池",
          spry: "华理认知实习（大三本科生）",
          pxsj: "2020-12-11",
          pxks: "2",
          rc: "50",
          zks: "100",
          fy: "400",
          fyqx: "培训费打卡",
          jsqk: "结算",
          jssj: "2021-1-12",
          rzsj: "2021-1-12",
          fyfsbm: "生产管理部",
        },
        {
          num: "35",
          type: "新进人员培训",
          content: "生产装置现场参观",
          bm: "催化剂装置",
          sz: "陈超",
          spry: "华理认知实习（大三本科生）",
          pxsj: "2020-12-11",
          pxks: "2",
          rc: "50",
          zks: "100",
          fy: "400",
          fyqx: "培训费打卡",
          jsqk: "结算",
          jssj: "2021-1-12",
          rzsj: "2021-1-12",
          fyfsbm: "催化剂装置-管理",
        },
        {
          num: "36",
          type: "新进人员培训",
          content: "公用工程、罐区介绍",
          bm: "丙烯酸装置",
          sz: "谢华剑",
          spry: "华理认知实习（大四本科生）",
          pxsj: "2020-12-14",
          pxks: "2",
          rc: "50",
          zks: "100",
          fy: "400",
          fyqx: "培训费打卡",
          jsqk: "结算",
          jssj: "2021-1-12",
          rzsj: "2021-1-12",
          fyfsbm: "丙烯酸装置-管理",
        },
        {
          num: "37",
          type: "新进人员培训",
          content: "化工机械设备的应用",
          bm: "生产管理部",
          sz: "赵晨兴",
          spry: "华理认知实习（大四本科生）",
          pxsj: "2020-12-14",
          pxks: "2",
          rc: "50",
          zks: "100",
          fy: "400",
          fyqx: "培训费打卡",
          jsqk: "结算",
          jssj: "2021-1-12",
          rzsj: "2021-1-12",
          fyfsbm: "生产管理部",
        },
        {
          num: "38",
          type: "新进人员培训",
          content: "仪表自动化在化工企业的应用",
          bm: "生产管理部",
          sz: "黄振飞",
          spry: "华理认知实习（大四本科生）",
          pxsj: "2020-12-15",
          pxks: "2",
          rc: "50",
          zks: "100",
          fy: "400",
          fyqx: "培训费打卡",
          jsqk: "未结算",
          jssj: "领导费用暂不结算",
          fyfsbm: "生产管理部",
        },
        {
          num: "39",
          type: "新进人员培训",
          content: "电气工程在化工企业的应用",
          bm: "生产管理部",
          sz: "龚磊",
          spry: "华理认知实习（大四本科生）",
          pxsj: "2020-12-15",
          pxks: "2",
          rc: "50",
          zks: "100",
          fy: "400",
          fyqx: "培训费打卡",
          jsqk: "结算",
          jssj: "2021-1-12",
          rzsj: "2021-1-12",
          fyfsbm: "生产管理部",
        },
        {
          num: "40",
          type: "新进人员培训",
          content: "学长经验分享交流",
          bm: "生产管理部",
          sz: "汪伟",
          spry: "华理认知实习（大四本科生）",
          pxsj: "2020-12-15",
          pxks: "1",
          rc: "50",
          zks: "50",
          fy: "300",
          fyqx: "培训费打卡",
          jsqk: "结算",
          jssj: "2021-1-12",
          rzsj: "2021-1-12",
          fyfsbm: "生产管理部",
        },
        {
          num: "41",
          type: "新进人员培训",
          content: "学长经验分享交流",
          bm: "丙烯酸装置",
          sz: "马振轲",
          spry: "华理认知实习（大四本科生）",
          pxsj: "2020-12-15",
          pxks: "1",
          rc: "50",
          zks: "50",
          fy: "300",
          fyqx: "培训费打卡",
          jsqk: "结算",
          jssj: "2021-1-12",
          rzsj: "2021-1-12",
          fyfsbm: "丙烯酸装置-管理",
        },
        {
          num: "42",
          type: "技能培训",
          content: "年度承包商安全培训",
          bm: "安全环保部",
          sz: "王斌",
          spry: "各承包商",
          pxsj: "2020/12/16-17",
          pxks: "16",
          rc: "50",
          zks: "800",
          fy: "800",
          fyqx: "培训费打卡",
          jsqk: "未结算",
          jssj: "领导费用暂不结算",
          fyfsbm: "安全环保部",
        },
        {
          num: "43",
          type: "技能培训",
          content: "化工总控工中级工培训",
          bm: "人力资源部",
          sz: "华谊党校",
          spry: "王士强",
          pxsj: "2020-12-21",
          pxks: "32",
          rc: "1",
          zks: "32",
          fy: "1000",
          fyqx: "共享报销",
          jsqk: "结算",
          jssj: "2021-3-8",
          rzsj: "2021-3-8",
          fyfsbm: "催化剂装置-生产",
        },
        {
          num: "44",
          type: "技能培训",
          content: "化工总控工中级工培训",
          bm: "人力资源部",
          sz: "华谊党校",
          spry: "薛春荣",
          pxsj: "2020-12-21",
          pxks: "32",
          rc: "1",
          zks: "32",
          fy: "1000",
          fyqx: "共享报销",
          jsqk: "结算",
          jssj: "2021-3-8",
          rzsj: "2021-3-8",
          fyfsbm: "SAP装置-生产",
        },
        {
          num: "45",
          type: "技能培训",
          content: "化工总控工中级工培训",
          bm: "人力资源部",
          sz: "华谊党校",
          spry: "蔡宇峰",
          pxsj: "2020-12-21",
          pxks: "32",
          rc: "1",
          zks: "32",
          fy: "1000",
          fyqx: "共享报销",
          jsqk: "结算",
          jssj: "2021-3-8",
          rzsj: "2021-3-8",
          fyfsbm: "丙烯酸装置-生产",
        },
        {
          num: "46",
          type: "技能培训",
          content: "化工总控工中级工培训",
          bm: "人力资源部",
          sz: "华谊党校",
          spry: "许立",
          pxsj: "2020-12-21",
          pxks: "32",
          rc: "1",
          zks: "32",
          fy: "1000",
          fyqx: "共享报销",
          jsqk: "结算",
          jssj: "2021-3-8",
          rzsj: "2021-3-8",
          fyfsbm: "丙烯酸装置-生产",
        },
        {
          num: "47",
          type: "技能培训",
          content: "化工总控工中级工培训",
          bm: "人力资源部",
          sz: "华谊党校",
          spry: "陆军军",
          pxsj: "2020-12-21",
          pxks: "32",
          rc: "1",
          zks: "32",
          fy: "1000",
          fyqx: "共享报销",
          jsqk: "结算",
          jssj: "2021-3-8",
          rzsj: "2021-3-8",
          fyfsbm: "丙烯酸装置-生产",
        },
        {
          num: "48",
          type: "技能培训",
          content: "化工总控工中级工培训",
          bm: "人力资源部",
          sz: "华谊党校",
          spry: "顾超锋",
          pxsj: "2020-12-21",
          pxks: "32",
          rc: "1",
          zks: "32",
          fy: "1000",
          fyqx: "共享报销",
          jsqk: "结算",
          jssj: "2021-3-8",
          rzsj: "2021-3-8",
          fyfsbm: "丙烯酸装置-生产",
        },
        {
          num: "49",
          type: "技能培训",
          content: "化工总控工中级工培训",
          bm: "人力资源部",
          sz: "华谊党校",
          spry: "陆嘉雯",
          pxsj: "2020-12-21",
          pxks: "32",
          rc: "1",
          zks: "32",
          fy: "1000",
          fyqx: "共享报销",
          jsqk: "结算",
          jssj: "2021-3-8",
          rzsj: "2021-3-8",
          fyfsbm: "丙烯酸装置-生产",
        },
        {
          num: "50",
          type: "技能培训",
          content: "化工总控工中级工培训",
          bm: "人力资源部",
          sz: "华谊党校",
          spry: "彭诗怡",
          pxsj: "2020-12-21",
          pxks: "32",
          rc: "1",
          zks: "32",
          fy: "1000",
          fyqx: "共享报销",
          jsqk: "结算",
          jssj: "2021-3-8",
          rzsj: "2021-3-8",
          fyfsbm: "丙烯酸装置-生产",
        },
        {
          num: "51",
          type: "技能培训",
          content: "化工总控工中级工培训",
          bm: "人力资源部",
          sz: "华谊党校",
          spry: "马浩伟",
          pxsj: "2020-12-21",
          pxks: "32",
          rc: "1",
          zks: "32",
          fy: "1000",
          fyqx: "共享报销",
          jsqk: "结算",
          jssj: "2021-7-19",
          rzsj: "2021-7-19",
          fyfsbm: "丙烯酸装置-生产",
        },
        {
          num: "52",
          type: "技能培训",
          content: "化工总控工中级工培训",
          bm: "人力资源部",
          sz: "华谊党校",
          spry: "王佳豪",
          pxsj: "2020-12-21",
          pxks: "32",
          rc: "1",
          zks: "32",
          fy: "1000",
          fyqx: "共享报销",
          jsqk: "结算",
          jssj: "2021-3-8",
          rzsj: "2021-3-8",
          fyfsbm: "丙烯酸装置-生产",
        },
        {
          num: "53",
          type: "技能培训",
          content: "化工总控工中级工培训",
          bm: "人力资源部",
          sz: "华谊党校",
          spry: "陈帆峰",
          pxsj: "2020-12-21",
          pxks: "32",
          rc: "1",
          zks: "32",
          fy: "1000",
          fyqx: "共享报销",
          jsqk: "结算",
          jssj: "2021-3-8",
          rzsj: "2021-3-8",
          fyfsbm: "丙烯酸装置-生产",
        },
        {
          num: "54",
          type: "技能培训",
          content: "化工总控工中级工培训",
          bm: "人力资源部",
          sz: "华谊党校",
          spry: "曹瑛杰",
          pxsj: "2020-12-21",
          pxks: "32",
          rc: "1",
          zks: "32",
          fy: "1000",
          fyqx: "共享报销",
          jsqk: "结算",
          jssj: "2021-3-8",
          rzsj: "2021-3-8",
          fyfsbm: "丙烯酸装置-生产",
        },
        {
          num: "55",
          type: "技能培训",
          content: "化工总控工中级工培训",
          bm: "人力资源部",
          sz: "华谊党校",
          spry: "陈诚",
          pxsj: "2020-12-21",
          pxks: "32",
          rc: "1",
          zks: "32",
          fy: "1000",
          fyqx: "共享报销",
          jsqk: "结算",
          jssj: "2021-3-8",
          rzsj: "2021-3-8",
          fyfsbm: "丙烯酸装置-生产",
        },
        {
          num: "56",
          type: "技能培训",
          content: "化工总控工中级工培训",
          bm: "人力资源部",
          sz: "华谊党校",
          spry: "吴叶帆",
          pxsj: "2020-12-21",
          pxks: "32",
          rc: "1",
          zks: "32",
          fy: "1000",
          fyqx: "共享报销",
          jsqk: "结算",
          jssj: "2021-3-8",
          rzsj: "2021-3-8",
          fyfsbm: "丙烯酸装置-生产",
        },
        {
          num: "57",
          type: "技能培训",
          content: "化工总控工中级工培训",
          bm: "人力资源部",
          sz: "华谊党校",
          spry: "朱鼎",
          pxsj: "2020-12-21",
          pxks: "32",
          rc: "1",
          zks: "32",
          fy: "1000",
          fyqx: "共享报销",
          jsqk: "结算",
          jssj: "2021-3-8",
          rzsj: "2021-3-8",
          fyfsbm: "丙烯酸装置-生产",
        },
        {
          num: "58",
          type: "技能培训",
          content: "年度承包商安全培训",
          bm: "安全环保部",
          sz: "何军峰",
          spry: "各承包商",
          pxsj: "2020-12-21",
          pxks: "8",
          rc: "50",
          zks: "400",
          fy: "400",
          fyqx: "培训费打卡",
          jsqk: "结算",
          jssj: "2021-1-12",
          rzsj: "2021-1-12",
          fyfsbm: "安全环保部",
        },
        {
          num: "59",
          type: "专业能力培训",
          content: "职业卫生防范培训",
          bm: "安全环保部",
          sz: "朱彩菊",
          spry: "各部门(装置）",
          pxsj: "2020-12-23",
          pxks: "4",
          rc: "50",
          zks: "200",
          fy: "2000",
          fyqx: "共享报销",
          jsqk: "结算",
          jssj: "2021-1-14",
          rzsj: "2021-1-14",
          fyfsbm: "安全环保部",
        },
        {
          num: "60",
          type: "学历教育",
          content: "西南交通大学 大专 一次性奖励",
          bm: "质检中心",
          sz: "西南交通大学",
          spry: "周钟",
          pxsj: "2021",
          rc: "1",
          zks: "0",
          fy: "500",
          fyqx: "培训费打卡",
          jsqk: "结算",
          jssj: "2021-4-26",
          rzsj: "2021-4-26",
          fyfsbm: "质检中心",
        },
        {
          num: "61",
          type: "技能培训",
          content: "2020年12月、2021年度第一季度带教费",
          bm: "丙烯酸装置",
          sz: "黄韻明",
          spry: "张健",
          pxsj: "2021",
          pxks: "120",
          rc: "1",
          zks: "120",
          fy: "900",
          fyqx: "培训费打卡",
          jsqk: "结算",
          jssj: "2021-1-12",
          rzsj: "2021-1-12",
          fyfsbm: "丙烯酸装置-生产",
        },
        {
          num: "62",
          type: "技能培训",
          content: "2020年12月、2021年度第一季度带教费",
          bm: "催化剂装置",
          sz: "秦春华",
          spry: "史乾源",
          pxsj: "2021",
          pxks: "120",
          rc: "1",
          zks: "120",
          fy: "900",
          fyqx: "培训费打卡",
          jsqk: "未结算",
          jssj: "领导费用暂不结算",
          fyfsbm: "催化剂装置-管理",
        },
        {
          num: "63",
          type: "技能培训",
          content: "2020年12月、2021年度第一季度带教费",
          bm: "催化剂装置",
          sz: "杨柳青",
          spry: "王士强",
          pxsj: "2021",
          pxks: "120",
          rc: "1",
          zks: "120",
          fy: "1200",
          fyqx: "培训费打卡",
          jsqk: "结算",
          jssj: "2021-1-12",
          rzsj: "2021-1-12",
          fyfsbm: "催化剂装置-生产",
        },
        {
          num: "64",
          type: "技能培训",
          content: "2020年12月、2021年度第一季度带教费",
          bm: "催化剂装置",
          sz: "杨柳青",
          spry: "鲍志鹏",
          pxsj: "2021",
          pxks: "120",
          rc: "1",
          zks: "120",
          fy: "0",
          fyqx: "培训费打卡",
          jsqk: "结算",
          jssj: "2021-1-12",
          rzsj: "2021-1-12",
          fyfsbm: "催化剂装置-生产",
        },
        {
          num: "65",
          type: "技能培训",
          content: "2020年12月、2021年度第一季度带教费",
          bm: "催化剂装置",
          sz: "张伟清",
          spry: "顾宇翀",
          pxsj: "2021",
          pxks: "120",
          rc: "1",
          zks: "120",
          fy: "900",
          fyqx: "培训费打卡",
          jsqk: "结算",
          jssj: "2021-1-12",
          rzsj: "2021-1-12",
          fyfsbm: "催化剂装置-生产",
        },
        {
          num: "66",
          type: "技能培训",
          content: "2020年12月、2021年度第一季度带教费",
          bm: "催化剂装置",
          sz: "李冬",
          spry: "王渊哲",
          pxsj: "2021",
          pxks: "120",
          rc: "1",
          zks: "120",
          fy: "900",
          fyqx: "培训费打卡",
          jsqk: "结算",
          jssj: "2021-1-12",
          rzsj: "2021-1-12",
          fyfsbm: "催化剂装置-生产",
        },
        {
          num: "67",
          type: "技能培训",
          content: "2020年12月、2021年度第一季度带教费",
          bm: "催化剂装置",
          sz: "高雪城",
          spry: "唐琦恒",
          pxsj: "2021",
          pxks: "120",
          rc: "1",
          zks: "120",
          fy: "900",
          fyqx: "培训费打卡",
          jsqk: "结算",
          jssj: "2021-1-12",
          rzsj: "2021-1-12",
          fyfsbm: "催化剂装置-生产",
        },
        {
          num: "68",
          type: "技能培训",
          content: "2020年12月、2021年度第一季度带教费",
          bm: "丙烯酸装置",
          sz: "贾苗苗",
          spry: "马振轲",
          pxsj: "2021",
          pxks: "40",
          rc: "1",
          zks: "40",
          fy: "600",
          fyqx: "培训费打卡",
          jsqk: "结算",
          jssj: "2021-1-12",
          rzsj: "2021-1-12",
          fyfsbm: "丙烯酸装置-管理",
        },
        {
          num: "69",
          type: "技能培训",
          content: "2020年12月、2021年度第一季度带教费",
          bm: "丙烯酸装置",
          sz: "冯彪",
          spry: "汪勇",
          pxsj: "2021",
          pxks: "40",
          rc: "1",
          zks: "40",
          fy: "300",
          fyqx: "培训费打卡",
          jsqk: "未结算",
          jssj: "领导费用暂不结算",
          fyfsbm: "丙烯酸装置-管理",
        },
        {
          num: "70",
          type: "技能培训",
          content: "2020年12月、2021年度第一季度带教费",
          bm: "丙烯酸装置",
          sz: "谢华剑",
          spry: "赵志鹏",
          pxsj: "2021",
          pxks: "40",
          rc: "1",
          zks: "40",
          fy: "300",
          fyqx: "培训费打卡",
          jsqk: "结算",
          jssj: "2021-1-12",
          rzsj: "2021-1-12",
          fyfsbm: "丙烯酸装置-管理",
        },
        {
          num: "71",
          type: "技能培训",
          content: "2020年12月、2021年度第一季度带教费",
          bm: "丙烯酸装置",
          sz: "贾苗苗",
          spry: "朱铭燕",
          pxsj: "2021",
          pxks: "40",
          rc: "1",
          zks: "40",
          fy: "0",
          fyqx: "培训费打卡",
          jsqk: "结算",
          jssj: "2021-1-12",
          rzsj: "2021-1-12",
          fyfsbm: "丙烯酸装置-管理",
        },
        {
          num: "72",
          type: "技能培训",
          content: "2020年12月、2021年度第一季度带教费",
          bm: "丙烯酸装置",
          sz: "贾苗苗",
          spry: "陈文良",
          pxsj: "2021",
          pxks: "40",
          rc: "1",
          zks: "40",
          fy: "0",
          fyqx: "培训费打卡",
          jsqk: "结算",
          jssj: "2021-1-12",
          rzsj: "2021-1-12",
          fyfsbm: "丙烯酸装置-管理",
        },
        {
          num: "73",
          type: "技能培训",
          content: "2020年12月、2021年度第一季度带教费",
          bm: "丙烯酸装置",
          sz: "李益",
          spry: "杨程鹏",
          pxsj: "2021",
          pxks: "40",
          rc: "1",
          zks: "40",
          fy: "400",
          fyqx: "培训费打卡",
          jsqk: "结算",
          jssj: "2021-1-12",
          rzsj: "2021-1-12",
          fyfsbm: "丙烯酸装置-管理",
        },
        {
          num: "74",
          type: "技能培训",
          content: "2020年12月、2021年度第一季度带教费",
          bm: "丙烯酸装置",
          sz: "李益",
          spry: "赵倩",
          pxsj: "2021",
          pxks: "40",
          rc: "1",
          zks: "40",
          fy: "0",
          fyqx: "培训费打卡",
          jsqk: "结算",
          jssj: "2021-1-12",
          rzsj: "2021-1-12",
          fyfsbm: "丙烯酸装置-管理",
        },
        {
          num: "75",
          type: "技能培训",
          content: "2020年12月、2021年度第一季度带教费",
          bm: "丙烯酸装置",
          sz: "汤杰",
          spry: "凌候彬",
          pxsj: "2021",
          pxks: "120",
          rc: "1",
          zks: "120",
          fy: "900",
          fyqx: "培训费打卡",
          jsqk: "结算",
          jssj: "2021-1-12",
          rzsj: "2021-1-12",
          fyfsbm: "丙烯酸装置-生产",
        },
        {
          num: "76",
          type: "技能培训",
          content: "2020年12月、2021年度第一季度带教费",
          bm: "丙烯酸装置",
          sz: "马伟",
          spry: "黄耀辉",
          pxsj: "2021",
          pxks: "120",
          rc: "1",
          zks: "120",
          fy: "1200",
          fyqx: "培训费打卡",
          jsqk: "结算",
          jssj: "2021-1-12",
          rzsj: "2021-1-12",
          fyfsbm: "丙烯酸装置-生产",
        },
        {
          num: "77",
          type: "技能培训",
          content: "2020年12月、2021年度第一季度带教费",
          bm: "丙烯酸装置",
          sz: "方涛",
          spry: "朱鼎",
          pxsj: "2021",
          pxks: "120",
          rc: "1",
          zks: "120",
          fy: "900",
          fyqx: "培训费打卡",
          jsqk: "结算",
          jssj: "2021-1-12",
          rzsj: "2021-1-12",
          fyfsbm: "丙烯酸装置-生产",
        },
        {
          num: "78",
          type: "技能培训",
          content: "2020年12月、2021年度第一季度带教费",
          bm: "丙烯酸装置",
          sz: "马伟",
          spry: "李成",
          pxsj: "2021",
          pxks: "120",
          rc: "1",
          zks: "120",
          fy: "0",
          fyqx: "培训费打卡",
          jsqk: "结算",
          jssj: "2021-1-12",
          rzsj: "2021-1-12",
          fyfsbm: "丙烯酸装置-生产",
        },
        {
          num: "79",
          type: "技能培训",
          content: "2020年12月、2021年度第一季度带教费",
          bm: "丙烯酸装置",
          sz: "江叶",
          spry: "曾炜",
          pxsj: "2021",
          pxks: "120",
          rc: "1",
          zks: "120",
          fy: "1200",
          fyqx: "培训费打卡",
          jsqk: "结算",
          jssj: "2021-1-12",
          rzsj: "2021-1-12",
          fyfsbm: "丙烯酸装置-生产",
        },
        {
          num: "80",
          type: "技能培训",
          content: "2020年12月、2021年度第一季度带教费",
          bm: "丙烯酸装置",
          sz: "江叶",
          spry: "陆军军",
          pxsj: "2021",
          pxks: "120",
          rc: "1",
          zks: "120",
          fy: "0",
          fyqx: "培训费打卡",
          jsqk: "结算",
          jssj: "2021-1-12",
          rzsj: "2021-1-12",
          fyfsbm: "丙烯酸装置-生产",
        },
        {
          num: "81",
          type: "技能培训",
          content: "2020年12月、2021年度第一季度带教费",
          bm: "丙烯酸装置",
          sz: "盛欢欢",
          spry: "许立",
          pxsj: "2021",
          pxks: "120",
          rc: "1",
          zks: "120",
          fy: "900",
          fyqx: "培训费打卡",
          jsqk: "结算",
          jssj: "2021-1-12",
          rzsj: "2021-1-12",
          fyfsbm: "丙烯酸装置-生产",
        },
        {
          num: "82",
          type: "技能培训",
          content: "2020年12月、2021年度第一季度带教费",
          bm: "丙烯酸装置",
          sz: "李琼",
          spry: "朱安",
          pxsj: "2021",
          pxks: "120",
          rc: "1",
          zks: "120",
          fy: "900",
          fyqx: "培训费打卡",
          jsqk: "结算",
          jssj: "2021-1-12",
          rzsj: "2021-1-12",
          fyfsbm: "丙烯酸装置-生产",
        },
        {
          num: "83",
          type: "技能培训",
          content: "蒸汽平衡及联锁处理培训",
          bm: "丙烯酸装置",
          sz: "冯彪",
          spry: "各班组正副班长、内操",
          pxsj: "2021.1.5-1.8",
          pxks: "2",
          rc: "26",
          zks: "52",
          fy: "800",
          fyqx: "培训费打卡",
          jsqk: "未结算",
          jssj: "领导费用暂不结算",
          fyfsbm: "丙烯酸装置-管理",
        },
        {
          num: "84",
          type: "技能培训",
          content: "中和反应PID图",
          bm: "SAP装置",
          sz: "朱习华",
          spry: "操作人员",
          pxsj: "2021-1-5",
          pxks: "2",
          rc: "16",
          zks: "32",
          fy: "200",
          fyqx: "培训费打卡",
          jsqk: "结算",
          jssj: "2021-7-23",
          rzsj: "2021-7-23",
        },
        {
          num: "85",
          type: "新进人员培训",
          content: "氧化工艺与蒸汽工艺知识了解",
          bm: "丙烯酸装置",
          sz: "汪勇",
          spry: "广西华谊新材料丙烯酸装置操作人员",
          pxsj: "2021-1-5",
          pxks: "2",
          rc: "45",
          zks: "90",
          fy: "200",
          fyqx: "培训费打卡",
          jsqk: "结算",
          jssj: "2021-4-26",
          rzsj: "2021-4-26",
          fyfsbm: "丙烯酸装置-管理",
        },
        {
          num: "86",
          type: "新进人员培训",
          content: "安全知识讲解",
          bm: "丙烯酸装置",
          sz: "周烨",
          spry: "广西华谊新材料丙烯酸装置操作人员",
          pxsj: "2021-1-5",
          pxks: "2",
          rc: "45",
          zks: "90",
          fy: "200",
          fyqx: "培训费打卡",
          jsqk: "结算",
          jssj: "2021-4-26",
          rzsj: "2021-4-26",
          fyfsbm: "丙烯酸装置-管理",
        },
        {
          num: "87",
          type: "新进人员培训",
          content: "621.622单元工艺介绍",
          bm: "丙烯酸装置",
          sz: "杨程鹏",
          spry: "广西华谊新材料丙烯酸装置操作人员",
          pxsj: "2021-1-6",
          pxks: "2",
          rc: "45",
          zks: "90",
          fy: "200",
          fyqx: "培训费打卡",
          jsqk: "结算",
          jssj: "2021-4-26",
          rzsj: "2021-4-26",
          fyfsbm: "丙烯酸装置-管理",
        },
        {
          num: "88",
          type: "新进人员培训",
          content: "丙烯酸丁酯单元介绍",
          bm: "丙烯酸装置",
          sz: "赵志鹏",
          spry: "广西华谊新材料丙烯酸装置操作人员",
          pxsj: "2021-1-6",
          pxks: "2",
          rc: "46",
          zks: "92",
          fy: "200",
          fyqx: "培训费打卡",
          jsqk: "结算",
          jssj: "2021-4-26",
          rzsj: "2021-4-26",
          fyfsbm: "丙烯酸装置-管理",
        },
        {
          num: "89",
          type: "新进人员培训",
          content: "静设备简介、固件及故障分析",
          bm: "丙烯酸装置",
          sz: "倪伟国",
          spry: "广西华谊新材料丙烯酸装置操作人员",
          pxsj: "2021-1-7",
          pxks: "2",
          rc: "46",
          zks: "92",
          fy: "200",
          fyqx: "培训费打卡",
          jsqk: "结算",
          jssj: "2021-4-26",
          rzsj: "2021-4-26",
          fyfsbm: "丙烯酸装置-管理",
        },
        {
          num: "90",
          type: "新进人员培训",
          content: "动设备相关及润滑油知识",
          bm: "丙烯酸装置",
          sz: "黄苍昊",
          spry: "广西华谊新材料丙烯酸装置操作人员",
          pxsj: "2021-1-7",
          pxks: "2",
          rc: "46",
          zks: "92",
          fy: "200",
          fyqx: "培训费打卡",
          jsqk: "结算",
          jssj: "2021-4-26",
          rzsj: "2021-4-26",
          fyfsbm: "丙烯酸装置-管理",
        },
        {
          num: "91",
          type: "新进人员培训",
          content: "机泵、设备基础知识与单机操作",
          bm: "丙烯酸装置",
          sz: "沈雷",
          spry: "广西华谊新材料丙烯酸装置操作人员",
          pxsj: "2021-1-8",
          pxks: "4",
          rc: "48",
          zks: "192",
          fy: "400",
          fyqx: "培训费打卡",
          jsqk: "结算",
          jssj: "2021-4-26",
          rzsj: "2021-4-26",
          fyfsbm: "丙烯酸装置-生产",
        },
        {
          num: "92",
          type: "新进人员培训",
          content: "丙烯单元PID图讲解、包括E01蒸汽置换接收PP及操作要点",
          bm: "丙烯酸装置",
          sz: "范冬冬",
          spry: "广西华谊新材料丙烯酸装置操作人员",
          pxsj: "2021-1-9",
          pxks: "2",
          rc: "47",
          zks: "94",
          fy: "200",
          fyqx: "培训费打卡",
          jsqk: "结算",
          jssj: "2021-4-26",
          rzsj: "2021-4-26",
          fyfsbm: "丙烯酸装置-生产",
        },
        {
          num: "93",
          type: "新进人员培训",
          content: "111单元空气、尾气PID图讲解、压缩机操作等",
          bm: "丙烯酸装置",
          sz: "范冬冬",
          spry: "广西华谊新材料丙烯酸装置操作人员",
          pxsj: "2021-1-9",
          pxks: "2",
          rc: "47",
          zks: "94",
          fy: "200",
          fyqx: "培训费打卡",
          jsqk: "结算",
          jssj: "2021-4-26",
          rzsj: "2021-4-26",
          fyfsbm: "丙烯酸装置-生产",
        },
        {
          num: "94",
          type: "取复证培训",
          content: "A特种设备安全管理",
          bm: "生产管理部",
          sz: "太平洋进修学校",
          spry: "龚海",
          pxsj: "2021-1-10",
          pxks: "8",
          rc: "1",
          zks: "8",
          fy: "400",
          fyqx: "共享报销",
          jsqk: "结算",
          jssj: "2021-1-28",
          rzsj: "2021-1-28",
          fyfsbm: "生产管理部",
        },
        {
          num: "95",
          type: "取复证培训",
          content: "A特种设备安全管理",
          bm: "催化剂装置",
          sz: "太平洋进修学校",
          spry: "吕剑峰",
          pxsj: "2021-1-10",
          pxks: "8",
          rc: "1",
          zks: "8",
          fy: "400",
          fyqx: "共享报销",
          jsqk: "结算",
          jssj: "2021-1-28",
          rzsj: "2021-1-28",
          fyfsbm: "催化剂装置-管理",
        },
        {
          num: "96",
          type: "取复证培训",
          content: "G3锅炉水处理",
          bm: "质检中心",
          sz: "太平洋进修学校",
          spry: "孙志俊",
          pxsj: "2021-1-10",
          pxks: "8",
          rc: "1",
          zks: "8",
          fy: "400",
          fyqx: "共享报销",
          jsqk: "结算",
          jssj: "2021-1-28",
          rzsj: "2021-1-28",
          fyfsbm: "质检中心",
        },
        {
          num: "97",
          type: "取复证培训",
          content: "G3锅炉水处理",
          bm: "质检中心",
          sz: "太平洋进修学校",
          spry: "谭雯琰",
          pxsj: "2021-1-10",
          pxks: "8",
          rc: "1",
          zks: "8",
          fy: "400",
          fyqx: "共享报销",
          jsqk: "结算",
          jssj: "2021-1-28",
          rzsj: "2021-1-28",
          fyfsbm: "质检中心",
        },
        {
          num: "98",
          type: "取复证培训",
          content: "G3锅炉水处理",
          bm: "质检中心",
          sz: "太平洋进修学校",
          spry: "周钟",
          pxsj: "2021-1-10",
          pxks: "8",
          rc: "1",
          zks: "8",
          fy: "400",
          fyqx: "共享报销",
          jsqk: "结算",
          jssj: "2021-1-28",
          rzsj: "2021-1-28",
          fyfsbm: "质检中心",
        },
        {
          num: "99",
          type: "取复证培训",
          content: "G3锅炉水处理",
          bm: "质检中心",
          sz: "太平洋进修学校",
          spry: "陈少武",
          pxsj: "2021-1-10",
          pxks: "8",
          rc: "1",
          zks: "8",
          fy: "400",
          fyqx: "共享报销",
          jsqk: "结算",
          jssj: "2021-1-28",
          rzsj: "2021-1-28",
          fyfsbm: "质检中心",
        },
        {
          num: "100",
          type: "取复证培训",
          content: "G3锅炉水处理",
          bm: "质检中心",
          sz: "太平洋进修学校",
          spry: "顾建国",
          pxsj: "2021-1-10",
          pxks: "8",
          rc: "1",
          zks: "8",
          fy: "400",
          fyqx: "共享报销",
          jsqk: "结算",
          jssj: "2021-1-28",
          rzsj: "2021-1-28",
          fyfsbm: "质检中心",
        },
        {
          num: "101",
          type: "取复证培训",
          content: "G3锅炉水处理",
          bm: "质检中心",
          sz: "太平洋进修学校",
          spry: "金欣培",
          pxsj: "2021-1-10",
          pxks: "8",
          rc: "1",
          zks: "8",
          fy: "400",
          fyqx: "共享报销",
          jsqk: "结算",
          jssj: "2021-1-28",
          rzsj: "2021-1-28",
          fyfsbm: "质检中心",
        },
        {
          num: "102",
          type: "取复证培训",
          content: "G3锅炉水处理",
          bm: "质检中心",
          sz: "太平洋进修学校",
          spry: "张子君",
          pxsj: "2021-1-10",
          pxks: "8",
          rc: "1",
          zks: "8",
          fy: "400",
          fyqx: "共享报销",
          jsqk: "结算",
          jssj: "2021-1-28",
          rzsj: "2021-1-28",
          fyfsbm: "质检中心",
        },
        {
          num: "103",
          type: "取复证培训",
          content: "G3锅炉水处理",
          bm: "质检中心",
          sz: "太平洋进修学校",
          spry: "金晓雯",
          pxsj: "2021-1-10",
          pxks: "8",
          rc: "1",
          zks: "8",
          fy: "400",
          fyqx: "共享报销",
          jsqk: "结算",
          jssj: "2021-1-28",
          rzsj: "2021-1-28",
          fyfsbm: "质检中心",
        },
        {
          num: "104",
          type: "取复证培训",
          content: "G3锅炉水处理",
          bm: "质检中心",
          sz: "太平洋进修学校",
          spry: "俞伟",
          pxsj: "2021-1-10",
          pxks: "8",
          rc: "1",
          zks: "8",
          fy: "400",
          fyqx: "共享报销",
          jsqk: "结算",
          jssj: "2021-1-28",
          rzsj: "2021-1-28",
          fyfsbm: "质检中心",
        },
        {
          num: "105",
          type: "取复证培训",
          content: "G3锅炉水处理",
          bm: "质检中心",
          sz: "太平洋进修学校",
          spry: "马卫成",
          pxsj: "2021-1-10",
          pxks: "8",
          rc: "1",
          zks: "8",
          fy: "400",
          fyqx: "共享报销",
          jsqk: "结算",
          jssj: "2021-1-28",
          rzsj: "2021-1-28",
          fyfsbm: "质检中心",
        },
        {
          num: "106",
          type: "取复证培训",
          content: "G3锅炉水处理",
          bm: "质检中心",
          sz: "太平洋进修学校",
          spry: "黄峰",
          pxsj: "2021-1-10",
          pxks: "8",
          rc: "1",
          zks: "8",
          fy: "400",
          fyqx: "共享报销",
          jsqk: "结算",
          jssj: "2021-1-28",
          rzsj: "2021-1-28",
          fyfsbm: "质检中心",
        },
        {
          num: "107",
          type: "新进人员培训",
          content: "R01.R02 PID图讲解及操作要点",
          bm: "丙烯酸装置",
          sz: "沈雷",
          spry: "广西华谊新材料丙烯酸装置操作人员",
          pxsj: "2021-1-12",
          pxks: "2",
          rc: "47",
          zks: "94",
          fy: "200",
          fyqx: "培训费打卡",
          jsqk: "结算",
          jssj: "2021-4-26",
          rzsj: "2021-4-26",
          fyfsbm: "丙烯酸装置-生产",
        },
        {
          num: "108",
          type: "新进人员培训",
          content: "C10.C20  PID图讲解及操作要点",
          bm: "丙烯酸装置",
          sz: "沈雷",
          spry: "广西华谊新材料丙烯酸装置操作人员",
          pxsj: "2021-1-12",
          pxks: "2",
          rc: "47",
          zks: "94",
          fy: "200",
          fyqx: "培训费打卡",
          jsqk: "结算",
          jssj: "2021-4-26",
          rzsj: "2021-4-26",
          fyfsbm: "丙烯酸装置-生产",
        },
        {
          num: "109",
          type: "技能培训",
          content: "骨干班组长研修培训",
          bm: "SAP装置",
          sz: "华谊党校",
          spry: "梁斌",
          pxsj: "2021/1/12-2021/1/14",
          pxks: "24",
          rc: "1",
          zks: "24",
          fy: "0",
          fyqx: "无费用",
          jsqk: "结算",
          jssj: "2021-1-12",
          rzsj: "2021-1-12",
          fyfsbm: "SAP装置-生产",
        },
        {
          num: "110",
          type: "专业能力培训",
          content: "安全相关培训",
          bm: "催化剂装置",
          sz: "陈超",
          spry: "张海涛、王宏亮、史乾源、高韵之",
          pxsj: "2021-1-13",
          pxks: "2",
          rc: "4",
          zks: "8",
          fy: "200",
          fyqx: "培训费打卡",
          jsqk: "结算",
          jssj: "2021-4-26",
          rzsj: "2021-4-26",
          fyfsbm: "催化剂装置-管理",
        },
        {
          num: "111",
          type: "党务培训",
          content: "发展对象培训",
          bm: "人力资源部",
          sz: "华谊党校",
          spry: "王巍",
          pxsj: "2021/1/13-1/15",
          pxks: "24",
          rc: "1",
          zks: "24",
          fy: "0",
          fyqx: "无费用",
          jsqk: "结算",
        },
        {
          num: "112",
          type: "党务培训",
          content: "发展对象培训",
          bm: "销售公司",
          sz: "华谊党校",
          spry: "傅欣杰",
          pxsj: "2021/1/13-1/15",
          pxks: "24",
          rc: "1",
          zks: "24",
          fy: "0",
          fyqx: "无费用",
          jsqk: "结算",
        },
        {
          num: "113",
          type: "新进人员培训",
          content: "111C30.E34.R40.C50 PID图讲解及操作要点",
          bm: "丙烯酸装置",
          sz: "王旭冬",
          spry: "广西华谊新材料丙烯酸装置操作人员",
          pxsj: "2021-1-13",
          pxks: "4",
          rc: "47",
          zks: "188",
          fy: "400",
          fyqx: "培训费打卡",
          jsqk: "结算",
          jssj: "2021-4-26",
          rzsj: "2021-4-26",
          fyfsbm: "丙烯酸装置-生产",
        },
        {
          num: "114",
          type: "新进人员培训",
          content: "丁酯单元生产简介、流程和操作要点、开停车操作",
          bm: "丙烯酸装置",
          sz: "王文坚",
          spry: "广西华谊新材料丙烯酸装置操作人员",
          pxsj: "2021-1-14",
          pxks: "4",
          rc: "47",
          zks: "188",
          fy: "400",
          fyqx: "培训费打卡",
          jsqk: "结算",
          jssj: "2021-4-26",
          rzsj: "2021-4-26",
          fyfsbm: "丙烯酸装置-生产",
        },
        {
          num: "115",
          type: "新进人员培训",
          content: "联锁介绍、历史上的今天",
          bm: "丙烯酸装置",
          sz: "陈宇",
          spry: "广西华谊新材料丙烯酸装置操作人员",
          pxsj: "2021-1-14",
          pxks: "4",
          rc: "47",
          zks: "188",
          fy: "400",
          fyqx: "培训费打卡",
          jsqk: "结算",
          jssj: "2021-4-26",
          rzsj: "2021-4-26",
          fyfsbm: "丙烯酸装置-生产",
        },
        {
          num: "116",
          type: "新进人员培训",
          content: "GAA单元生产要点和操作矩阵讲解",
          bm: "丙烯酸装置",
          sz: "范冬冬",
          spry: "广西华谊新材料丙烯酸装置操作人员",
          pxsj: "2021-1-19",
          pxks: "2",
          rc: "43",
          zks: "86",
          fy: "200",
          fyqx: "培训费打卡",
          jsqk: "结算",
          jssj: "2021-4-26",
          rzsj: "2021-4-26",
          fyfsbm: "丙烯酸装置-生产",
        },
        {
          num: "117",
          type: "新进人员培训",
          content: "821/621单元生产操作要点和蒸汽平衡",
          bm: "丙烯酸装置",
          sz: "范冬冬",
          spry: "广西华谊新材料丙烯酸装置操作人员",
          pxsj: "2021-1-19",
          pxks: "2",
          rc: "43",
          zks: "86",
          fy: "200",
          fyqx: "培训费打卡",
          jsqk: "结算",
          jssj: "2021-4-26",
          rzsj: "2021-4-26",
          fyfsbm: "丙烯酸装置-生产",
        },
        {
          num: "118",
          type: "技能培训",
          content: "化学室实验器材基本操作培训",
          bm: "质检中心",
          sz: "谭雯琰",
          spry: "倒班人员",
          pxsj: "2021-1-19",
          pxks: "2",
          rc: "17",
          zks: "34",
          fy: "200",
          fyqx: "培训费打卡",
          jsqk: "结算",
          jssj: "2021-4-26",
          rzsj: "2021-4-26",
          fyfsbm: "质检中心",
        },
        {
          num: "119",
          type: "专业能力培训",
          content: "复泰一月课程《数字化人才招聘与面试秘籍》",
          bm: "人力资源部",
          sz: "复泰管理学院",
          spry: "陈珂可",
          pxsj: "2021-1-19",
          pxks: "8",
          rc: "1",
          zks: "8",
          fy: "0",
          fyqx: "共享报销",
          jsqk: "结算",
          jssj: "年初已统一结算",
          fyfsbm: "人力资源部",
        },
        {
          num: "120",
          type: "取复证培训",
          content: "G2电站锅炉司炉",
          bm: "丙烯酸装置",
          sz: "太平洋进修学校",
          spry: "王旭冬",
          pxsj: "2021-1-22",
          pxks: "8",
          rc: "1",
          zks: "8",
          fy: "400",
          fyqx: "共享报销",
          jsqk: "结算",
          jssj: "2021-1-28",
          rzsj: "2021-1-28",
          fyfsbm: "丙烯酸装置-生产",
        },
        {
          num: "121",
          type: "取复证培训",
          content: "G2电站锅炉司炉",
          bm: "丙烯酸装置",
          sz: "太平洋进修学校",
          spry: "范冬冬",
          pxsj: "2021-1-22",
          pxks: "8",
          rc: "1",
          zks: "8",
          fy: "400",
          fyqx: "共享报销",
          jsqk: "结算",
          jssj: "2021-1-28",
          rzsj: "2021-1-28",
          fyfsbm: "丙烯酸装置-生产",
        },
        {
          num: "122",
          type: "取复证培训",
          content: "G2电站锅炉司炉",
          bm: "SAP装置",
          sz: "太平洋进修学校",
          spry: "梁斌",
          pxsj: "2021-1-22",
          pxks: "8",
          rc: "1",
          zks: "8",
          fy: "400",
          fyqx: "共享报销",
          jsqk: "结算",
          jssj: "2021-1-28",
          rzsj: "2021-1-28",
          fyfsbm: "SAP装置-生产",
        },
        {
          num: "123",
          type: "取复证培训",
          content: "G2电站锅炉司炉",
          bm: "丙烯酸装置",
          sz: "太平洋进修学校",
          spry: "朱海飙",
          pxsj: "2021-1-22",
          pxks: "8",
          rc: "1",
          zks: "8",
          fy: "400",
          fyqx: "共享报销",
          jsqk: "结算",
          jssj: "2021-1-28",
          rzsj: "2021-1-28",
          fyfsbm: "丙烯酸装置-生产",
        },
        {
          num: "124",
          type: "取复证培训",
          content: "G2电站锅炉司炉",
          bm: "丙烯酸装置",
          sz: "太平洋进修学校",
          spry: "汤杰",
          pxsj: "2021-1-22",
          pxks: "8",
          rc: "1",
          zks: "8",
          fy: "400",
          fyqx: "共享报销",
          jsqk: "结算",
          jssj: "2021-1-28",
          rzsj: "2021-1-28",
          fyfsbm: "丙烯酸装置-生产",
        },
        {
          num: "125",
          type: "取复证培训",
          content: "G2电站锅炉司炉",
          bm: "丙烯酸装置",
          sz: "太平洋进修学校",
          spry: "方涛",
          pxsj: "2021-1-22",
          pxks: "8",
          rc: "1",
          zks: "8",
          fy: "400",
          fyqx: "共享报销",
          jsqk: "结算",
          jssj: "2021-1-28",
          rzsj: "2021-1-28",
          fyfsbm: "丙烯酸装置-生产",
        },
        {
          num: "126",
          type: "取复证培训",
          content: "G2电站锅炉司炉",
          bm: "丙烯酸装置",
          sz: "太平洋进修学校",
          spry: "徐佳健",
          pxsj: "2021-1-22",
          pxks: "8",
          rc: "1",
          zks: "8",
          fy: "400",
          fyqx: "共享报销",
          jsqk: "结算",
          jssj: "2021-1-28",
          rzsj: "2021-1-28",
          fyfsbm: "丙烯酸装置-生产",
        },
        {
          num: "127",
          type: "取复证培训",
          content: "G2电站锅炉司炉",
          bm: "丙烯酸装置",
          sz: "太平洋进修学校",
          spry: "马伟",
          pxsj: "2021-1-22",
          pxks: "8",
          rc: "1",
          zks: "8",
          fy: "400",
          fyqx: "共享报销",
          jsqk: "结算",
          jssj: "2021-1-28",
          rzsj: "2021-1-28",
          fyfsbm: "丙烯酸装置-生产",
        },
        {
          num: "128",
          type: "取复证培训",
          content: "G2电站锅炉司炉",
          bm: "丙烯酸装置",
          sz: "太平洋进修学校",
          spry: "胡金铭",
          pxsj: "2021-1-22",
          pxks: "8",
          rc: "1",
          zks: "8",
          fy: "400",
          fyqx: "共享报销",
          jsqk: "结算",
          jssj: "2021-1-28",
          rzsj: "2021-1-28",
          fyfsbm: "丙烯酸装置-生产",
        },
        {
          num: "129",
          type: "取复证培训",
          content: "G2电站锅炉司炉",
          bm: "丙烯酸装置",
          sz: "太平洋进修学校",
          spry: "李琼",
          pxsj: "2021-1-22",
          pxks: "8",
          rc: "1",
          zks: "8",
          fy: "400",
          fyqx: "共享报销",
          jsqk: "结算",
          jssj: "2021-1-28",
          rzsj: "2021-1-28",
          fyfsbm: "丙烯酸装置-生产",
        },
        {
          num: "130",
          type: "取复证培训",
          content: "G2电站锅炉司炉",
          bm: "丙烯酸装置",
          sz: "太平洋进修学校",
          spry: "朱虹",
          pxsj: "2021-1-22",
          pxks: "8",
          rc: "1",
          zks: "8",
          fy: "400",
          fyqx: "共享报销",
          jsqk: "结算",
          jssj: "2021-1-28",
          rzsj: "2021-1-28",
          fyfsbm: "丙烯酸装置-生产",
        },
        {
          num: "131",
          type: "取复证培训",
          content: "G2电站锅炉司炉",
          bm: "丙烯酸装置",
          sz: "太平洋进修学校",
          spry: "朱玉峰",
          pxsj: "2021-1-22",
          pxks: "8",
          rc: "1",
          zks: "8",
          fy: "400",
          fyqx: "共享报销",
          jsqk: "结算",
          jssj: "2021-1-28",
          rzsj: "2021-1-28",
          fyfsbm: "丙烯酸装置-生产",
        },
        {
          num: "132",
          type: "取复证培训",
          content: "G2电站锅炉司炉",
          bm: "丙烯酸装置",
          sz: "太平洋进修学校",
          spry: "方亮亮",
          pxsj: "2021-1-22",
          pxks: "8",
          rc: "1",
          zks: "8",
          fy: "400",
          fyqx: "共享报销",
          jsqk: "结算",
          jssj: "2021-1-28",
          rzsj: "2021-1-28",
          fyfsbm: "丙烯酸装置-生产",
        },
        {
          num: "133",
          type: "取复证培训",
          content: "G2电站锅炉司炉",
          bm: "丙烯酸装置",
          sz: "太平洋进修学校",
          spry: "沈瑞",
          pxsj: "2021-1-22",
          pxks: "8",
          rc: "1",
          zks: "8",
          fy: "400",
          fyqx: "共享报销",
          jsqk: "结算",
          jssj: "2021-1-28",
          rzsj: "2021-1-28",
          fyfsbm: "丙烯酸装置-生产",
        },
        {
          num: "134",
          type: "取复证培训",
          content: "G2电站锅炉司炉",
          bm: "丙烯酸装置",
          sz: "太平洋进修学校",
          spry: "沈婷婷",
          pxsj: "2021-1-22",
          pxks: "8",
          rc: "1",
          zks: "8",
          fy: "400",
          fyqx: "共享报销",
          jsqk: "结算",
          jssj: "2021-1-28",
          rzsj: "2021-1-28",
          fyfsbm: "丙烯酸装置-生产",
        },
        {
          num: "135",
          type: "取复证培训",
          content: "G2电站锅炉司炉",
          bm: "丙烯酸装置",
          sz: "太平洋进修学校",
          spry: "张敏",
          pxsj: "2021-1-22",
          pxks: "8",
          rc: "1",
          zks: "8",
          fy: "400",
          fyqx: "共享报销",
          jsqk: "结算",
          jssj: "2021-1-28",
          rzsj: "2021-1-28",
          fyfsbm: "丙烯酸装置-生产",
        },
        {
          num: "136",
          type: "取复证培训",
          content: "G2电站锅炉司炉",
          bm: "丙烯酸装置",
          sz: "太平洋进修学校",
          spry: "黄思思",
          pxsj: "2021-1-22",
          pxks: "8",
          rc: "1",
          zks: "8",
          fy: "400",
          fyqx: "共享报销",
          jsqk: "结算",
          jssj: "2021-1-28",
          rzsj: "2021-1-28",
          fyfsbm: "丙烯酸装置-生产",
        },
        {
          num: "137",
          type: "取复证培训",
          content: "G2电站锅炉司炉",
          bm: "丙烯酸装置",
          sz: "太平洋进修学校",
          spry: "沈红",
          pxsj: "2021-1-22",
          pxks: "8",
          rc: "1",
          zks: "8",
          fy: "400",
          fyqx: "共享报销",
          jsqk: "结算",
          jssj: "2021-1-28",
          rzsj: "2021-1-28",
          fyfsbm: "丙烯酸装置-生产",
        },
        {
          num: "138",
          type: "取复证培训",
          content: "G2电站锅炉司炉",
          bm: "丙烯酸装置",
          sz: "太平洋进修学校",
          spry: "陈晶晶",
          pxsj: "2021-1-22",
          pxks: "8",
          rc: "1",
          zks: "8",
          fy: "400",
          fyqx: "共享报销",
          jsqk: "结算",
          jssj: "2021-1-28",
          rzsj: "2021-1-28",
          fyfsbm: "丙烯酸装置-生产",
        },
        {
          num: "139",
          type: "取复证培训",
          content: "G2电站锅炉司炉",
          bm: "丙烯酸装置",
          sz: "太平洋进修学校",
          spry: "徐峰",
          pxsj: "2021-1-22",
          pxks: "8",
          rc: "1",
          zks: "8",
          fy: "400",
          fyqx: "共享报销",
          jsqk: "结算",
          jssj: "2021-1-28",
          rzsj: "2021-1-28",
          fyfsbm: "丙烯酸装置-生产",
        },
        {
          num: "140",
          type: "取复证培训",
          content: "G2电站锅炉司炉",
          bm: "丙烯酸装置",
          sz: "太平洋进修学校",
          spry: "江叶",
          pxsj: "2021-1-22",
          pxks: "8",
          rc: "1",
          zks: "8",
          fy: "400",
          fyqx: "共享报销",
          jsqk: "结算",
          jssj: "2021-1-28",
          rzsj: "2021-1-28",
          fyfsbm: "丙烯酸装置-生产",
        },
        {
          num: "141",
          type: "取复证培训",
          content: "G2电站锅炉司炉",
          bm: "丙烯酸装置",
          sz: "太平洋进修学校",
          spry: "顾金龙",
          pxsj: "2021-1-22",
          pxks: "8",
          rc: "1",
          zks: "8",
          fy: "400",
          fyqx: "共享报销",
          jsqk: "结算",
          jssj: "2021-1-28",
          rzsj: "2021-1-28",
          fyfsbm: "丙烯酸装置-生产",
        },
        {
          num: "142",
          type: "取复证培训",
          content: "G2电站锅炉司炉",
          bm: "丙烯酸装置",
          sz: "太平洋进修学校",
          spry: "盛欢欢",
          pxsj: "2021-1-22",
          pxks: "8",
          rc: "1",
          zks: "8",
          fy: "400",
          fyqx: "共享报销",
          jsqk: "结算",
          jssj: "2021-1-28",
          rzsj: "2021-1-28",
          fyfsbm: "丙烯酸装置-生产",
        },
        {
          num: "143",
          type: "取复证培训",
          content: "G2电站锅炉司炉",
          bm: "丙烯酸装置",
          sz: "太平洋进修学校",
          spry: "尤惊春",
          pxsj: "2021-1-22",
          pxks: "8",
          rc: "1",
          zks: "8",
          fy: "400",
          fyqx: "共享报销",
          jsqk: "结算",
          jssj: "2021-1-28",
          rzsj: "2021-1-28",
          fyfsbm: "丙烯酸装置-生产",
        },
        {
          num: "144",
          type: "取复证培训",
          content: "G2电站锅炉司炉",
          bm: "丙烯酸装置",
          sz: "太平洋进修学校",
          spry: "朱安",
          pxsj: "2021-1-22",
          pxks: "8",
          rc: "1",
          zks: "8",
          fy: "400",
          fyqx: "共享报销",
          jsqk: "结算",
          jssj: "2021-1-28",
          rzsj: "2021-1-28",
          fyfsbm: "丙烯酸装置-生产",
        },
        {
          num: "145",
          type: "取复证培训",
          content: "G2电站锅炉司炉",
          bm: "丙烯酸装置",
          sz: "太平洋进修学校",
          spry: "徐天成",
          pxsj: "2021-1-22",
          pxks: "8",
          rc: "1",
          zks: "8",
          fy: "400",
          fyqx: "共享报销",
          jsqk: "结算",
          jssj: "2021-1-28",
          rzsj: "2021-1-28",
          fyfsbm: "丙烯酸装置-生产",
        },
      ],
      saveData: [],
    };
  },
  mounted() {
    // 保存原始数据
    this.saveData = JSON.parse(JSON.stringify(this.tableData));
  },
  methods: {
    handleSearch() {
      this.tableData = this.saveData.filter((item) => {
        let nameKey = "planName";
        let contentKey = "content";
        let dateKey = "startDate1";

        let nameIn = this.searchForm[nameKey]
          ? item[nameKey].indexOf(this.searchForm[nameKey]) >= 0
          : true;
        let contentIn = this.searchForm[contentKey]
          ? item[contentKey].indexOf(this.searchForm[contentKey]) >= 0
          : true;

        let sDate = this.searchForm[dateKey][0];
        let eDate = this.searchForm[dateKey][1];

        console.log(sDate);

        let getTimeFromStr = (str) => {
          return new Date(str).getTime();
        };

        let dateIn =
          sDate && eDate
            ? getTimeFromStr(item[dateKey]) <= eDate.getTime() &&
              getTimeFromStr(item[dateKey]) >= sDate.getTime()
            : true;

        return nameIn && contentIn && dateIn;
      });
    },
    handleReset() {
      this.tableData = JSON.parse(JSON.stringify(this.saveData));
      this.searchForm = {
        startDate1: [],
        planName: "",
        content: "",
      };
    },
  },
};
</script>

<style scoped lang="less">
.testplan {
  padding: 20px;
  text-align: left;
}
.form-outer {
  margin-bottom: 10px;
  display: flex;
  flex-wrap: wrap;
  .item {
    width: 200px;
    margin-right: 10px;
  }
  .label {
    line-height: 40px;
  }
}
</style>